version: "3.7"

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./init_db.py:/app/init_db.py
      - ./requirements.txt:/app/requirements.txt
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - prometheus
  prometheus: # 1. 'influxdb' -> 'prometheus'로 변경
    image: prom/prometheus:latest # 2. ARM64를 지원하는 공식 이미지
    container_name: prometheus
    ports:
      - "9090:9090" # 3. Prometheus 기본 포트
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml # 4. Prometheus 설정 파일 마운트
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver" # 5. k6가 데이터를 쓸 수 있게 함 (매우 중요)
  granafa:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    depends_on:
      - prometheus
